

FEATURES = ['ship',
            'x_max', 'x_min', 'x_mean', 'x_std', 'x_skew', 'x_sum',
            'y_max', 'y_min','y_mean', 'y_std', 'y_skew', 'y_sum',
            'v_max', 'v_min', 'v_mean', 'v_std', 'v_skew','v_sum',
            'd_max', 'd_min', 'd_mean', 'd_std', 'd_skew', 'd_sum',
            'x_max_min','x_max_min_mean', 'x_max_min_std', 'y_max_min', 'y_max_min_mean', 'y_max_min_std',
            'v_max_min', 'v_max_min_mean', 'v_max_min_std', 'd_max_min', 'd_max_min_mean', 'd_max_min_std',
            'x_1_level_prop', 'x_2_level_prop', 'x_3_level_prop', 'x_4_level_prop', 'x_5_level_prop','x_6_level_prop', 'x_7_level_prop', 'x_8_level_prop', 'x_9_level_prop', 'x_10_level_prop',
            'x_1_level_num', 'x_2_level_num', 'x_3_level_num', 'x_4_level_num', 'x_5_level_num', 'x_6_level_num','x_7_level_num', 'x_8_level_num', 'x_9_level_num', 'x_10_level_num',
            'y_1_level_prop', 'y_2_level_prop','y_3_level_prop', 'y_4_level_prop', 'y_5_level_prop', 'y_6_level_prop', 'y_7_level_prop', 'y_8_level_prop','y_9_level_prop', 'y_10_level_prop',
            'y_1_level_num', 'y_2_level_num', 'y_3_level_num', 'y_4_level_num', 'y_5_level_num', 'y_6_level_num', 'y_7_level_num', 'y_8_level_num', 'y_9_level_num', 'y_10_level_num',
            'v_1_level_prop', 'v_2_level_prop', 'v_3_level_prop', 'v_4_level_prop', 'v_5_level_prop', 'v_6_level_prop', 'v_7_level_prop', 'v_8_level_prop', 'v_9_level_prop', 'v_10_level_prop',
            'v_1_level_num', 'v_2_level_num', 'v_3_level_num', 'v_4_level_num', 'v_5_level_num', 'v_6_level_num', 'v_7_level_num', 'v_8_level_num', 'v_9_level_num', 'v_10_level_num',
            'd_1_level_num', 'd_2_level_num', 'd_3_level_num', 'd_4_level_num', 'd_5_level_num', 'd_6_level_num', 'd_7_level_num', 'd_8_level_num', 'd_9_level_num', 'd_10_level_num',
            'd_11_level_num', 'd_12_level_num', 'd_1_level_prop', 'd_2_level_prop', 'd_3_level_prop', 'd_4_level_prop', 'd_5_level_prop', 'd_6_level_prop', 'd_7_level_prop', 'd_8_level_prop', 'd_9_level_prop', 'd_10_level_prop', 'd_11_level_prop', 'd_12_level_prop',
            'v_no_less_max', 'v_no_less_min', 'v_no_less_mean', 'v_no_less_std', 'v_no_less_skew', 'v_no_less_sum', 'v_no_less_max_min', 'v_no_less_max_min_mean', 'v_no_less_max_min_std',
            'v_less_num', 'v_less_prop', 'v_no_less_prop', 'v_zero_num', 'v_zero_prop', 'v_no_zero_prop',
            'lasting_days', 'x_less_prop', 'x_no_less_prop', 'y_less_prop', 'y_no_less_prop', 'type']

FEATURES_1 = ['ship', 'x_max', 'x_min', 'x_mean', 'x_std', 'x_skew', 'x_sum', 'y_max', 'y_min',
            'y_mean', 'y_std', 'y_skew', 'y_sum', 'v_max', 'v_min', 'v_mean', 'v_std', 'v_skew',
            'v_sum', 'd_max', 'd_min', 'd_mean', 'd_std', 'd_skew', 'd_sum', 'x_max_min',
            'x_max_min_mean', 'x_max_min_std', 'y_max_min', 'y_max_min_mean', 'y_max_min_std',
            'v_max_min', 'v_max_min_mean', 'v_max_min_std', 'd_max_min', 'd_max_min_mean', 'd_max_min_std',
            'x_1_level_prop', 'x_2_level_prop', 'x_3_level_prop', 'x_4_level_prop', 'x_5_level_prop','x_6_level_prop', 'x_7_level_prop', 'x_8_level_prop', 'x_9_level_prop', 'x_10_level_prop',
            'y_1_level_prop', 'y_2_level_prop','y_3_level_prop', 'y_4_level_prop', 'y_5_level_prop', 'y_6_level_prop', 'y_7_level_prop', 'y_8_level_prop','y_9_level_prop', 'y_10_level_prop',
            'v_1_level_prop', 'v_2_level_prop', 'v_3_level_prop', 'v_4_level_prop', 'v_5_level_prop','v_6_level_prop', 'v_7_level_prop', 'v_8_level_prop', 'v_9_level_prop', 'v_10_level_prop',
            'd_11_level_num', 'd_12_level_num', 'd_1_level_prop', 'd_2_level_prop', 'd_3_level_prop','d_4_level_prop', 'd_5_level_prop', 'd_6_level_prop', 'd_7_level_prop', 'd_8_level_prop',
            'd_9_level_prop', 'd_10_level_prop', 'd_11_level_prop', 'd_12_level_prop', 'v_no_less_max','v_no_less_min', 'v_no_less_mean', 'v_no_less_std', 'v_no_less_skew', 'v_no_less_sum',
            'v_no_less_max_min', 'v_no_less_max_min_mean', 'v_no_less_max_min_std', 'v_less_num','v_less_prop', 'v_no_less_prop', 'v_zero_num', 'v_zero_prop', 'v_no_zero_prop',
            'lasting_days', 'x_less_prop', 'x_no_less_prop', 'y_less_prop', 'y_no_less_prop', 'type']

FEATURES_2 = ['ship', 'x_max', 'x_min', 'x_mean', 'x_std', 'x_skew', 'x_sum', 'y_max', 'y_min',
            'y_mean', 'y_std', 'y_skew', 'y_sum', 'v_max', 'v_min', 'v_mean', 'v_std', 'v_skew',
            'v_sum', 'd_max', 'd_min', 'd_mean', 'd_std', 'd_skew', 'd_sum', 'x_max_min',
            'x_max_min_mean', 'x_max_min_std', 'y_max_min', 'y_max_min_mean', 'y_max_min_std',
            'v_max_min', 'v_max_min_mean', 'v_max_min_std', 'd_max_min', 'd_max_min_mean', 'd_max_min_std',
            'x_1_level_prop', 'x_2_level_prop', 'x_3_level_prop', 'x_4_level_prop', 'x_5_level_prop','x_6_level_prop', 'x_7_level_prop', 'x_8_level_prop', 'x_9_level_prop', 'x_10_level_prop',
            'y_1_level_prop', 'y_2_level_prop','y_3_level_prop', 'y_4_level_prop', 'y_5_level_prop', 'y_6_level_prop', 'y_7_level_prop', 'y_8_level_prop','y_9_level_prop', 'y_10_level_prop',
            'v_1_level_prop', 'v_2_level_prop', 'v_3_level_prop', 'v_4_level_prop', 'v_5_level_prop','v_6_level_prop', 'v_7_level_prop', 'v_8_level_prop', 'v_9_level_prop', 'v_10_level_prop',
            'd_11_level_num', 'd_12_level_num', 'd_1_level_prop', 'd_2_level_prop', 'd_3_level_prop','d_4_level_prop', 'd_5_level_prop', 'd_6_level_prop', 'd_7_level_prop', 'd_8_level_prop',
            'd_9_level_prop', 'd_10_level_prop', 'd_11_level_prop', 'd_12_level_prop',
            'v_no_less_max','v_no_less_min', 'v_no_less_mean', 'v_no_less_std', 'v_no_less_skew', 'v_no_less_sum', 'v_no_less_max_min', 'v_no_less_max_min_mean', 'v_no_less_max_min_std', 'v_less_prop', 'v_zero_prop',
            'lasting_days', 'x_less_prop', 'y_less_prop', 'type']